spring:
  application:
    name: sentinel-demo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        password: nacos
        username: nacos
    sentinel:
      transport:
        dashboard: 127.0.0.1:9100
      eager: true #取消控制台懒加载

server:
  port: 8181

#将所有可用的监控指标项对外暴露
#可以访问 /actuator/sentinel进行查看Sentinel监控项
management:
  endpoints:
    web:
      exposure:
        include: '*'